import type {
  ActionItem,
  ItemDef,
  Profession,
  ProfessionAction,
  ProfessionKey,
  ProfessionRankTier,
  Skill,
  SkillKey,
  Stat,
  StatKey,
  Zone,
  SeedItem,
} from './types'
import { computeExpToNext } from './experience'

const professionRanks: [ProfessionRankTier, ...ProfessionRankTier[]] = [
  { name: 'Novice', minLevel: 0, bonusMultiplier: 0 },
  { name: 'Apprentice', minLevel: 25, bonusMultiplier: 0.05 },
  { name: 'Journeyman', minLevel: 50, bonusMultiplier: 0.1 },
  { name: 'Adept', minLevel: 75, bonusMultiplier: 0.16 },
  { name: 'Expert', minLevel: 100, bonusMultiplier: 0.23 },
  { name: 'Master', minLevel: 125, bonusMultiplier: 0.31 },
  { name: 'Grandmaster', minLevel: 150, bonusMultiplier: 0.4 },
  { name: 'Mythic', minLevel: 175, bonusMultiplier: 0.5 },
  { name: 'Ascendant', minLevel: 200, bonusMultiplier: 0.62 },
]

export const createStats = (): Record<StatKey, Stat> => ({
  Strength: {
    name: 'Strength',
    value: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.2, 15),
    description: 'Power, lifting, melee force.',
  },
  Agility: {
    name: 'Agility',
    value: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.2, 15),
    description: 'Speed, reflexes, dexterity.',
  },
  Vitality: {
    name: 'Vitality',
    value: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.2, 15),
    description: 'Health, stamina, endurance.',
  },
  Spirit: {
    name: 'Spirit',
    value: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.2, 15),
    description: 'Mana, willpower, recovery.',
  },
  Intelligence: {
    name: 'Intelligence',
    value: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.2, 15),
    description: 'Knowledge, crafting, tactics.',
  },
})

export const createSkills = (): Record<SkillKey, Skill> => ({
  Combat: {
    name: 'Combat',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.22, 10),
    description: 'Weapon handling and battle instincts.',
  },
  Survival: {
    name: 'Survival',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.22, 10),
    description: 'Tracking, foraging, fieldcraft.',
  },
  Harvesting: {
    name: 'Harvesting',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.22, 10),
    description: 'Gathering resources and loot.',
  },
  Crafting: {
    name: 'Crafting',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.22, 10),
    description: 'Making gear and supplies.',
  },
  Arcana: {
    name: 'Arcana',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.22, 10),
    description: 'Mana control and spellwork.',
  },
})

export const createProfessions = (): Record<ProfessionKey, Profession> => ({
  Mining: {
    name: 'Mining',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.25, 15),
    maxLevel: 200,
    description: 'Extract ore and crystals from the Land.',
    bonusLabel: 'Yield bonus',
    bonusPerLevel: 0.03,
    rankTiers: professionRanks,
  },
  Herbalism: {
    name: 'Herbalism',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.25, 15),
    maxLevel: 200,
    description: 'Gather rare herbs and reagents.',
    bonusLabel: 'Yield bonus',
    bonusPerLevel: 0.03,
    rankTiers: professionRanks,
  },
  Smelting: {
    name: 'Smelting',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.25, 15),
    maxLevel: 200,
    description: 'Refine ores into usable ingots.',
    bonusLabel: 'Output bonus',
    bonusPerLevel: 0.02,
    rankTiers: professionRanks,
  },
  Alchemy: {
    name: 'Alchemy',
    level: 0,
    exp: 0,
    baseExpToNext: 100,
    expToNext: computeExpToNext(100, 0, 1.25, 15),
    maxLevel: 200,
    description: 'Brew tonics and mana infusions.',
    bonusLabel: 'Potency bonus',
    bonusPerLevel: 0.02,
    rankTiers: professionRanks,
  },
})

export const createProfessionActions = (): ProfessionAction[] => [
  {
    id: 'mine-copper-seam',
    profession: 'Mining',
    name: 'Copper Seam',
    description: 'Work shallow seams for basic copper ore.',
    requiredLevel: 0,
    expGain: 4,
    rewards: [{ itemId: 'copper-ore', amount: 3 }],
  },
  {
    id: 'mine-tin-run',
    profession: 'Mining',
    name: 'Tin Run',
    description: 'Extract brittle tin veins from mist-cut rock.',
    requiredLevel: 10,
    expGain: 6,
    rewards: [{ itemId: 'tin-ore', amount: 3 }],
  },
  {
    id: 'mine-iron-lode',
    profession: 'Mining',
    name: 'Iron Lode',
    description: 'Break into dense iron pockets in the foothills.',
    requiredLevel: 20,
    expGain: 8,
    rewards: [
      { itemId: 'iron-ore', amount: 4 },
    ],
  },
  {
    id: 'mine-silver-vein',
    profession: 'Mining',
    name: 'Silver Vein',
    description: 'Refined veins with sharper fracture lines.',
    requiredLevel: 35,
    expGain: 11,
    rewards: [{ itemId: 'silver-ore', amount: 3 }],
  },
  {
    id: 'mine-gold-pocket',
    profession: 'Mining',
    name: 'Gold Pocket',
    description: 'Narrow pockets that yield high-value ore.',
    requiredLevel: 50,
    expGain: 14,
    rewards: [{ itemId: 'gold-ore', amount: 3 }],
  },
  {
    id: 'mine-mithril-thread',
    profession: 'Mining',
    name: 'Mithril Thread',
    description: 'Rare luminous strands hidden in deeper strata.',
    requiredLevel: 75,
    expGain: 18,
    rewards: [{ itemId: 'mithril-ore', amount: 2 }],
  },
  {
    id: 'mine-adamantite-node',
    profession: 'Mining',
    name: 'Adamantite Node',
    description: 'Hard nodes that challenge even expert miners.',
    requiredLevel: 110,
    expGain: 23,
    rewards: [{ itemId: 'adamantite-ore', amount: 2 }],
  },
  {
    id: 'mine-orichalcum-heart',
    profession: 'Mining',
    name: 'Orichalcum Heart',
    description: 'Legend-grade ore embedded in mana-rich bedrock.',
    requiredLevel: 150,
    expGain: 30,
    rewards: [
      { itemId: 'orichalcum-ore', amount: 2 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
  },
  {
    id: 'herb-mist-herb-beds',
    profession: 'Herbalism',
    name: 'Mist Herb Beds',
    description: 'Harvest common herb patches around Mist Village.',
    requiredLevel: 0,
    expGain: 4,
    rewards: [{ itemId: 'mist-herb', amount: 3 }],
  },
  {
    id: 'herb-bitterleaf-thicket',
    profession: 'Herbalism',
    name: 'Bitterleaf Thicket',
    description: 'Gather bitterleaf from lowland thickets.',
    requiredLevel: 10,
    expGain: 6,
    rewards: [{ itemId: 'bitterleaf', amount: 3 }],
  },
  {
    id: 'herb-sungrass-prairie',
    profession: 'Herbalism',
    name: 'Sungrass Prairie',
    description: 'Clip resilient sungrass from open plains.',
    requiredLevel: 20,
    expGain: 8,
    rewards: [{ itemId: 'sungrass', amount: 3 }],
  },
  {
    id: 'herb-nightshade-veil',
    profession: 'Herbalism',
    name: 'Nightshade Veil',
    description: 'Pick volatile nightshade in shaded groves.',
    requiredLevel: 35,
    expGain: 11,
    rewards: [{ itemId: 'nightshade', amount: 3 }],
  },
  {
    id: 'herb-ghost-orchid-watch',
    profession: 'Herbalism',
    name: 'Ghost Orchid Watch',
    description: 'Track the pale bloom cycle in moonlit clearings.',
    requiredLevel: 50,
    expGain: 14,
    rewards: [{ itemId: 'ghost-orchid', amount: 2 }],
  },
  {
    id: 'herb-frost-lotus-pool',
    profession: 'Herbalism',
    name: 'Frost Lotus Pool',
    description: 'Harvest chilled lotus petals from mana-fed pools.',
    requiredLevel: 75,
    expGain: 18,
    rewards: [{ itemId: 'frost-lotus', amount: 2 }],
  },
  {
    id: 'herb-drakebloom-ridge',
    profession: 'Herbalism',
    name: 'Drakebloom Ridge',
    description: 'Collect heat-soaked drakebloom from volcanic ridges.',
    requiredLevel: 110,
    expGain: 23,
    rewards: [{ itemId: 'drakebloom', amount: 2 }],
  },
  {
    id: 'herb-void-thistle-rift',
    profession: 'Herbalism',
    name: 'Void Thistle Rift',
    description: 'Cut void thistle near unstable mana fractures.',
    requiredLevel: 150,
    expGain: 30,
    rewards: [
      { itemId: 'void-thistle', amount: 2 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
  },
  {
    id: 'smelt-copper',
    profession: 'Smelting',
    name: 'Smelt Copper',
    description: 'Refine copper ore into usable ingots.',
    requiredLevel: 0,
    expGain: 5,
    inputs: [{ itemId: 'copper-ore', amount: 3 }],
    rewards: [{ itemId: 'copper-ingot', amount: 1 }],
  },
  {
    id: 'smelt-tin',
    profession: 'Smelting',
    name: 'Smelt Tin',
    description: 'Refine tin ore for alloy and utility work.',
    requiredLevel: 10,
    expGain: 7,
    inputs: [{ itemId: 'tin-ore', amount: 3 }],
    rewards: [{ itemId: 'tin-ingot', amount: 1 }],
  },
  {
    id: 'smelt-iron',
    profession: 'Smelting',
    name: 'Smelt Iron',
    description: 'Refine dense iron ore into sturdy ingots.',
    requiredLevel: 20,
    expGain: 9,
    inputs: [{ itemId: 'iron-ore', amount: 3 }],
    rewards: [{ itemId: 'iron-ingot', amount: 1 }],
  },
  {
    id: 'smelt-silver',
    profession: 'Smelting',
    name: 'Smelt Silver',
    description: 'Smelt silver ore with controlled heat for purity.',
    requiredLevel: 35,
    expGain: 12,
    inputs: [{ itemId: 'silver-ore', amount: 3 }],
    rewards: [{ itemId: 'silver-ingot', amount: 1 }],
  },
  {
    id: 'smelt-gold',
    profession: 'Smelting',
    name: 'Smelt Gold',
    description: 'Refine malleable gold ore into bright ingots.',
    requiredLevel: 50,
    expGain: 15,
    inputs: [{ itemId: 'gold-ore', amount: 3 }],
    rewards: [{ itemId: 'gold-ingot', amount: 1 }],
  },
  {
    id: 'smelt-mithril',
    profession: 'Smelting',
    name: 'Smelt Mithril',
    description: 'Stabilize mithril ore at precise temperatures.',
    requiredLevel: 75,
    expGain: 19,
    inputs: [
      { itemId: 'mithril-ore', amount: 3 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'mithril-ingot', amount: 1 }],
  },
  {
    id: 'smelt-adamantite',
    profession: 'Smelting',
    name: 'Smelt Adamantite',
    description: 'Use reinforced crucibles to process adamantite.',
    requiredLevel: 110,
    expGain: 24,
    inputs: [
      { itemId: 'adamantite-ore', amount: 3 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'adamantite-ingot', amount: 1 }],
  },
  {
    id: 'smelt-orichalcum',
    profession: 'Smelting',
    name: 'Smelt Orichalcum',
    description: 'Channel mana through rift forges to bind orichalcum.',
    requiredLevel: 150,
    expGain: 32,
    inputs: [
      { itemId: 'orichalcum-ore', amount: 3 },
      { itemId: 'mana-crystal', amount: 2 },
    ],
    rewards: [{ itemId: 'orichalcum-ingot', amount: 1 }],
  },
  {
    id: 'alchemy-minor-elixir',
    profession: 'Alchemy',
    name: 'Brew Minor Tonic',
    description: 'Basic restorative mixture.',
    requiredLevel: 0,
    expGain: 5,
    inputs: [{ itemId: 'mist-herb', amount: 3 }],
    rewards: [{ itemId: 'minor-elixir', amount: 1 }],
  },
  {
    id: 'alchemy-focus-draught',
    profession: 'Alchemy',
    name: 'Focus Draught',
    description: 'A balanced draught for mana recovery and clarity.',
    requiredLevel: 10,
    expGain: 7,
    inputs: [
      { itemId: 'bitterleaf', amount: 4 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'focus-draught', amount: 1 }],
  },
  {
    id: 'alchemy-warding-tonic',
    profession: 'Alchemy',
    name: 'Warding Tonic',
    description: 'A protective brew that steadies body and mind.',
    requiredLevel: 20,
    expGain: 9,
    inputs: [
      { itemId: 'sungrass', amount: 4 },
      { itemId: 'tin-ingot', amount: 1 },
    ],
    rewards: [{ itemId: 'warding-tonic', amount: 1 }],
  },
  {
    id: 'alchemy-fury-philter',
    profession: 'Alchemy',
    name: 'Fury Philter',
    description: 'Aggressive stimulant favored by front-line fighters.',
    requiredLevel: 35,
    expGain: 12,
    inputs: [
      { itemId: 'nightshade', amount: 4 },
      { itemId: 'iron-ingot', amount: 1 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'fury-philter', amount: 1 }],
  },
  {
    id: 'alchemy-clarity-elixir',
    profession: 'Alchemy',
    name: 'Clarity Elixir',
    description: 'Arcane catalyst for focus and spell discipline.',
    requiredLevel: 50,
    expGain: 15,
    inputs: [
      { itemId: 'ghost-orchid', amount: 3 },
      { itemId: 'silver-ingot', amount: 1 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'clarity-elixir', amount: 1 }],
  },
  {
    id: 'alchemy-frostguard-draught',
    profession: 'Alchemy',
    name: 'Frostguard Draught',
    description: 'Cold-forged tonic that hardens vitality.',
    requiredLevel: 75,
    expGain: 19,
    inputs: [
      { itemId: 'frost-lotus', amount: 3 },
      { itemId: 'gold-ingot', amount: 1 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'frostguard-draught', amount: 1 }],
  },
  {
    id: 'alchemy-dragonfire-tonic',
    profession: 'Alchemy',
    name: 'Dragonfire Tonic',
    description: 'High-heat stimulant for brutal engagements.',
    requiredLevel: 110,
    expGain: 24,
    inputs: [
      { itemId: 'drakebloom', amount: 3 },
      { itemId: 'mithril-ingot', amount: 1 },
      { itemId: 'mana-crystal', amount: 2 },
    ],
    rewards: [{ itemId: 'dragonfire-tonic', amount: 1 }],
  },
  {
    id: 'alchemy-rift-essence',
    profession: 'Alchemy',
    name: 'Rift Essence',
    description: 'Mythic infusion distilled at rift threshold heat.',
    requiredLevel: 150,
    expGain: 32,
    inputs: [
      { itemId: 'void-thistle', amount: 3 },
      { itemId: 'orichalcum-ingot', amount: 1 },
      { itemId: 'mana-crystal', amount: 3 },
    ],
    rewards: [
      { itemId: 'rift-essence', amount: 1 },
    ],
  },
]

export const createActions = (): ActionItem[] => [
  {
    id: 'train-strength',
    name: 'Train Strength',
    description: 'Lift, strike, and grind power gains.',
    gains: {
      exp: 5,
      stats: { Strength: 7, Vitality: 3 },
      skills: { Combat: 3 },
    },
  },
  {
    id: 'forest-run',
    name: 'Forest Run',
    description: 'Sprint and weave through the wilds.',
    gains: {
      exp: 4,
      stats: { Agility: 6, Vitality: 2 },
      skills: { Survival: 3 },
    },
  },
  {
    id: 'meditate',
    name: 'Meditate',
    description: 'Focus the core and gather mana.',
    gains: {
      exp: 3,
      stats: { Spirit: 7, Intelligence: 3 },
      skills: { Arcana: 4 },
    },
  },
  {
    id: 'gather',
    name: 'Gather Herbs',
    description: 'Idle harvesting for simple income.',
    gains: {
      exp: 2,
      stats: { Agility: 1, Intelligence: 2 },
      skills: { Harvesting: 5 },
    },
  },
  {
    id: 'craft',
    name: 'Craft Supplies',
    description: 'Turn finds into coin and skill.',
    gains: {
      exp: 3,
      stats: { Intelligence: 5 },
      skills: { Crafting: 5 },
    },
  },
  {
    id: 'arcane-focus',
    name: 'Arcane Focus',
    description: 'Shape raw mana into insight and skill.',
    manaCost: 12,
    gains: {
      exp: 3,
      stats: { Intelligence: 6, Spirit: 2 },
      skills: { Arcana: 6 },
    },
  },
]

export const createItemDefs = (): Record<string, ItemDef> => ({
  'copper-ore': {
    id: 'copper-ore',
    name: 'Copper Ore',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Mining',
    description: 'A soft starter ore mined from shallow seams.',
    maxStack: 50,
    priceCopper: 1,
  },
  'tin-ore': {
    id: 'tin-ore',
    name: 'Tin Ore',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Mining',
    description: 'A pale ore often found near copper deposits.',
    maxStack: 50,
    priceCopper: 2,
  },
  'mist-herb': {
    id: 'mist-herb',
    name: 'Mist Herb',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'A fragrant herb used in basic potions.',
    maxStack: 50,
    priceCopper: 1,
  },
  bitterleaf: {
    id: 'bitterleaf',
    name: 'Bitterleaf',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'A sharp-tasting leaf used for hardy brews.',
    maxStack: 50,
    priceCopper: 2,
  },
  sungrass: {
    id: 'sungrass',
    name: 'Sungrass',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'Dry golden blades used in tonic bases.',
    maxStack: 50,
    priceCopper: 3,
  },
  nightshade: {
    id: 'nightshade',
    name: 'Nightshade',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'A volatile herb requiring careful handling.',
    maxStack: 40,
    priceCopper: 7,
  },
  'ghost-orchid': {
    id: 'ghost-orchid',
    name: 'Ghost Orchid',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'A pale bloom prized in advanced infusions.',
    maxStack: 35,
    priceCopper: 10,
  },
  'frost-lotus': {
    id: 'frost-lotus',
    name: 'Frost Lotus',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'Mana-chilled petals used for precision alchemy.',
    maxStack: 25,
    priceCopper: 20,
  },
  drakebloom: {
    id: 'drakebloom',
    name: 'Drakebloom',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'Heat-forged blossoms found near drake nests.',
    maxStack: 20,
    priceCopper: 34,
  },
  'void-thistle': {
    id: 'void-thistle',
    name: 'Void Thistle',
    quality: 'Epic',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'A dark thorned herb touched by rift mana.',
    maxStack: 15,
    priceCopper: 60,
  },
  'goblin-ear': {
    id: 'goblin-ear',
    name: 'Goblin Ear',
    quality: 'Uncommon',
    type: 'Quest',
    subtype: 'Trophy',
    description: 'Proof of a goblin raid defeated.',
    maxStack: 20,
    priceCopper: 5,
  },
  'iron-ore': {
    id: 'iron-ore',
    name: 'Iron Ore',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Mining',
    description: 'Dense raw ore favored by village smiths.',
    maxStack: 50,
    priceCopper: 3,
  },
  'silver-ore': {
    id: 'silver-ore',
    name: 'Silver Ore',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Mining',
    description: 'High-luster ore with strong arcane affinity.',
    maxStack: 50,
    priceCopper: 7,
  },
  'gold-ore': {
    id: 'gold-ore',
    name: 'Gold Ore',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Mining',
    description: 'Heavy ore prized by traders and crafters alike.',
    maxStack: 50,
    priceCopper: 10,
  },
  'mithril-ore': {
    id: 'mithril-ore',
    name: 'Mithril Ore',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Mining',
    description: 'Light, brilliant ore used in superior gear.',
    maxStack: 40,
    priceCopper: 22,
  },
  'adamantite-ore': {
    id: 'adamantite-ore',
    name: 'Adamantite Ore',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Mining',
    description: 'Extremely hard ore with exceptional durability.',
    maxStack: 35,
    priceCopper: 36,
  },
  'orichalcum-ore': {
    id: 'orichalcum-ore',
    name: 'Orichalcum Ore',
    quality: 'Epic',
    type: 'Resource',
    subtype: 'Mining',
    description: 'Legendary metal ore saturated with mana.',
    maxStack: 25,
    priceCopper: 65,
  },
  'mana-crystal': {
    id: 'mana-crystal',
    name: 'Mana Crystal',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Arcana',
    description: 'A crystal infused with condensed mana.',
    maxStack: 10,
    priceCopper: 5,
  },
  'leather-helm': {
    id: 'leather-helm',
    name: 'Leather Helm',
    quality: 'Common',
    type: 'Equip',
    subtype: 'Helm',
    description: 'Basic protection for the head.',
    maxStack: 1,
    priceCopper: 25,
  },
  'iron-ingot': {
    id: 'iron-ingot',
    name: 'Iron Ingot',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Refined metal ready for crafting.',
    maxStack: 50,
    priceCopper: 5,
  },
  'copper-ingot': {
    id: 'copper-ingot',
    name: 'Copper Ingot',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Refined copper for basic crafting.',
    maxStack: 50,
    priceCopper: 4,
  },
  'tin-ingot': {
    id: 'tin-ingot',
    name: 'Tin Ingot',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Refined tin used in tools and alloys.',
    maxStack: 50,
    priceCopper: 5,
  },
  'silver-ingot': {
    id: 'silver-ingot',
    name: 'Silver Ingot',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Refined silver with strong magical conductivity.',
    maxStack: 40,
    priceCopper: 14,
  },
  'gold-ingot': {
    id: 'gold-ingot',
    name: 'Gold Ingot',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Precious metal ingot for high-value crafting.',
    maxStack: 40,
    priceCopper: 18,
  },
  'mithril-ingot': {
    id: 'mithril-ingot',
    name: 'Mithril Ingot',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Light and resilient ingot from mithril ore.',
    maxStack: 25,
    priceCopper: 36,
  },
  'adamantite-ingot': {
    id: 'adamantite-ingot',
    name: 'Adamantite Ingot',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Ultra-dense ingot suited for top-grade gear.',
    maxStack: 20,
    priceCopper: 55,
  },
  'orichalcum-ingot': {
    id: 'orichalcum-ingot',
    name: 'Orichalcum Ingot',
    quality: 'Epic',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'A mana-saturated ingot of legendary quality.',
    maxStack: 12,
    priceCopper: 95,
  },
  'minor-elixir': {
    id: 'minor-elixir',
    name: 'Minor Elixir',
    quality: 'Uncommon',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'A simple potion that refreshes vitality.',
    effectDescription: 'Restores 35 HP and grants 8 character XP.',
    maxStack: 10,
    priceCopper: 20,
  },
  'focus-draught': {
    id: 'focus-draught',
    name: 'Focus Draught',
    quality: 'Uncommon',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'A sharp, clear-toned tonic for arcane focus.',
    effectDescription: 'Restores 30 Mana and grants 12 character XP.',
    maxStack: 10,
    priceCopper: 28,
  },
  'warding-tonic': {
    id: 'warding-tonic',
    name: 'Warding Tonic',
    quality: 'Uncommon',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'A fortified blend that steadies body and mind.',
    effectDescription: 'Restores 55 HP and 20 Mana.',
    maxStack: 10,
    priceCopper: 36,
  },
  'fury-philter': {
    id: 'fury-philter',
    name: 'Fury Philter',
    quality: 'Rare',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'A volatile combat draught with intense kick.',
    effectDescription: 'Grants 26 character XP and 20 Combat skill XP.',
    maxStack: 8,
    priceCopper: 55,
  },
  'clarity-elixir': {
    id: 'clarity-elixir',
    name: 'Clarity Elixir',
    quality: 'Rare',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'Arcane reagent blend for disciplined casting.',
    effectDescription: 'Restores 60 Mana and grants 26 Arcana skill XP.',
    maxStack: 8,
    priceCopper: 68,
  },
  'frostguard-draught': {
    id: 'frostguard-draught',
    name: 'Frostguard Draught',
    quality: 'Rare',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'A chilled tonic that hardens endurance.',
    effectDescription: 'Restores 90 HP and grants 18 Vitality stat XP.',
    maxStack: 6,
    priceCopper: 88,
  },
  'dragonfire-tonic': {
    id: 'dragonfire-tonic',
    name: 'Dragonfire Tonic',
    quality: 'Epic',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'Superheated blend used before high-risk battles.',
    effectDescription: 'Grants 60 character XP, 45 Combat XP, and 30 Arcana XP.',
    maxStack: 5,
    priceCopper: 130,
  },
  'rift-essence': {
    id: 'rift-essence',
    name: 'Rift Essence',
    quality: 'Epic',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'Mythic condensation of rift-charged reagents.',
    effectDescription: 'Restores 130 HP, 130 Mana, and grants 100 character XP.',
    maxStack: 4,
    priceCopper: 200,
  },
})

export const seedInventoryItems: SeedItem[] = [
  { itemId: 'mist-herb', amount: 5 },
  { itemId: 'iron-ore', amount: 5 },
  { itemId: 'mana-crystal', amount: 2 },
]

export const createZones = (): Zone[] => [
  {
    id: 'mist-outskirts',
    name: 'Mist Village Outskirts',
    description: 'Wolves and bandits prowl the village edge.',
    levelMin: 1,
    levelMax: 5,
    basePower: 6,
    baseRewards: { exp: 16, copper: 10, skillExp: 6, statExp: 3 },
    enemies: [
      { id: 'wolf', name: 'Wild Wolf', powerFactor: 0.9, hpFactor: 0.9, rewardFactor: 0.9 },
      { id: 'bandit', name: 'Bandit Scout', powerFactor: 1.0, hpFactor: 1.0, rewardFactor: 1.0 },
      { id: 'boar', name: 'Dire Boar', powerFactor: 1.1, hpFactor: 1.15, rewardFactor: 1.1 },
    ],
  },
  {
    id: 'mist-forest',
    name: 'Mist Forest',
    description: 'Dense woods with lurking goblins.',
    levelMin: 4,
    levelMax: 8,
    basePower: 10,
    baseRewards: { exp: 22, copper: 14, skillExp: 7, statExp: 3 },
    enemies: [
      { id: 'goblin', name: 'Forest Goblin', powerFactor: 1.0, hpFactor: 0.95, rewardFactor: 1.0 },
      { id: 'stalker', name: 'Mist Stalker', powerFactor: 1.1, hpFactor: 1.05, rewardFactor: 1.1 },
      { id: 'spider', name: 'Shadow Spider', powerFactor: 0.95, hpFactor: 1.0, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'river-delle',
    name: 'River Delle',
    description: 'River spirits and crocodiles contest the banks.',
    levelMin: 7,
    levelMax: 12,
    basePower: 14,
    baseRewards: { exp: 28, copper: 18, skillExp: 8, statExp: 4 },
    enemies: [
      { id: 'croc', name: 'River Croc', powerFactor: 1.05, hpFactor: 1.15, rewardFactor: 1.1 },
      { id: 'sprite', name: 'River Sprite', powerFactor: 0.9, hpFactor: 0.85, rewardFactor: 0.9 },
      { id: 'lurker', name: 'Marsh Lurker', powerFactor: 1.0, hpFactor: 1.0, rewardFactor: 1.0 },
    ],
  },
  {
    id: 'goblin-warrens',
    name: 'Goblin Warrens',
    description: 'Tunnels under the hills, crawling with goblins.',
    levelMin: 10,
    levelMax: 15,
    basePower: 18,
    baseRewards: { exp: 34, copper: 24, skillExp: 10, statExp: 4 },
    enemies: [
      { id: 'raider', name: 'Goblin Raider', powerFactor: 1.0, hpFactor: 1.0, rewardFactor: 1.0 },
      { id: 'shaman', name: 'Goblin Shaman', powerFactor: 1.1, hpFactor: 0.95, rewardFactor: 1.1 },
      { id: 'brute', name: 'Goblin Brute', powerFactor: 1.2, hpFactor: 1.15, rewardFactor: 1.2 },
    ],
  },
  {
    id: 'shadow-fen',
    name: 'Shadow Fen',
    description: 'Swamp mists hide venom and undead.',
    levelMin: 14,
    levelMax: 20,
    basePower: 22,
    baseRewards: { exp: 40, copper: 30, skillExp: 12, statExp: 5 },
    enemies: [
      { id: 'stalker', name: 'Fen Stalker', powerFactor: 1.05, hpFactor: 1.0, rewardFactor: 1.05 },
      { id: 'bogwraith', name: 'Bog Wraith', powerFactor: 1.15, hpFactor: 0.9, rewardFactor: 1.15 },
      { id: 'slime', name: 'Toxic Slime', powerFactor: 0.95, hpFactor: 1.2, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'darkwood',
    name: 'Darkwood',
    description: 'Ancient trees and shadow beasts.',
    levelMin: 18,
    levelMax: 25,
    basePower: 26,
    baseRewards: { exp: 48, copper: 36, skillExp: 14, statExp: 5 },
    enemies: [
      { id: 'lynx', name: 'Shadow Lynx', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
      { id: 'treant', name: 'Darkwood Treant', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'shade', name: 'Night Shade', powerFactor: 1.0, hpFactor: 0.9, rewardFactor: 1.0 },
    ],
  },
  {
    id: 'stonefist-range',
    name: 'Stonefist Range',
    description: 'Rocky passes and ogre patrols.',
    levelMin: 22,
    levelMax: 30,
    basePower: 30,
    baseRewards: { exp: 58, copper: 44, skillExp: 16, statExp: 6 },
    enemies: [
      { id: 'ogre', name: 'Ogre Brute', powerFactor: 1.2, hpFactor: 1.25, rewardFactor: 1.2 },
      { id: 'bear', name: 'Stone Bear', powerFactor: 1.0, hpFactor: 1.1, rewardFactor: 1.0 },
      { id: 'raider', name: 'Cliff Raider', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
    ],
  },
  {
    id: 'silverpine-forest',
    name: 'Silverpine Forest',
    description: 'Silver bark and fey hunters.',
    levelMin: 26,
    levelMax: 34,
    basePower: 34,
    baseRewards: { exp: 66, copper: 52, skillExp: 18, statExp: 6 },
    enemies: [
      { id: 'fey', name: 'Fey Tracker', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
      { id: 'stag', name: 'Silver Stag', powerFactor: 0.95, hpFactor: 1.0, rewardFactor: 0.95 },
      { id: 'warden', name: 'Grove Warden', powerFactor: 1.15, hpFactor: 1.1, rewardFactor: 1.15 },
    ],
  },
  {
    id: 'great-plains',
    name: 'Great Plains',
    description: 'Stampedes and roaming beast packs.',
    levelMin: 30,
    levelMax: 38,
    basePower: 38,
    baseRewards: { exp: 74, copper: 60, skillExp: 20, statExp: 7 },
    enemies: [
      { id: 'ripper', name: 'Plains Ripper', powerFactor: 1.1, hpFactor: 1.0, rewardFactor: 1.1 },
      { id: 'hornbeast', name: 'Thunderhorn', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'scavenger', name: 'Sky Scavenger', powerFactor: 0.95, hpFactor: 0.9, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'ashen-barrens',
    name: 'Ashen Barrens',
    description: 'Scorched earth and ash drakes.',
    levelMin: 34,
    levelMax: 42,
    basePower: 42,
    baseRewards: { exp: 84, copper: 70, skillExp: 22, statExp: 7 },
    enemies: [
      { id: 'drake', name: 'Ash Drake', powerFactor: 1.2, hpFactor: 1.1, rewardFactor: 1.25 },
      { id: 'cinder', name: 'Cinder Hound', powerFactor: 1.0, hpFactor: 0.95, rewardFactor: 1.0 },
      { id: 'pyre', name: 'Pyre Elemental', powerFactor: 1.15, hpFactor: 1.2, rewardFactor: 1.2 },
    ],
  },
  {
    id: 'sunken-ruins',
    name: 'Sunken Ruins',
    description: 'Ancient halls submerged in mana tides.',
    levelMin: 38,
    levelMax: 46,
    basePower: 46,
    baseRewards: { exp: 94, copper: 82, skillExp: 24, statExp: 8 },
    enemies: [
      { id: 'sentinel', name: 'Ruins Sentinel', powerFactor: 1.15, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'warden', name: 'Abyss Warden', powerFactor: 1.1, hpFactor: 1.0, rewardFactor: 1.1 },
      { id: 'eel', name: 'Mana Eel', powerFactor: 0.95, hpFactor: 0.9, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'thunder-steppe',
    name: 'Thunder Steppe',
    description: 'Storm-charged beasts and lightning spirits.',
    levelMin: 42,
    levelMax: 50,
    basePower: 50,
    baseRewards: { exp: 104, copper: 94, skillExp: 26, statExp: 8 },
    enemies: [
      { id: 'charger', name: 'Storm Charger', powerFactor: 1.2, hpFactor: 1.1, rewardFactor: 1.2 },
      { id: 'sprite', name: 'Lightning Sprite', powerFactor: 0.95, hpFactor: 0.85, rewardFactor: 0.95 },
      { id: 'howler', name: 'Thunder Howler', powerFactor: 1.1, hpFactor: 1.05, rewardFactor: 1.1 },
    ],
  },
  {
    id: 'wyvern-cliffs',
    name: 'Wyvern Cliffs',
    description: 'Sheer cliffs ruled by winged predators.',
    levelMin: 46,
    levelMax: 54,
    basePower: 54,
    baseRewards: { exp: 116, copper: 110, skillExp: 28, statExp: 9 },
    enemies: [
      { id: 'wyvern', name: 'Cliff Wyvern', powerFactor: 1.2, hpFactor: 1.15, rewardFactor: 1.2 },
      { id: 'harpy', name: 'Sky Harpy', powerFactor: 1.05, hpFactor: 0.9, rewardFactor: 1.05 },
      { id: 'eagle', name: 'Ridge Eagle', powerFactor: 0.95, hpFactor: 0.85, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'crystal-caverns',
    name: 'Crystal Caverns',
    description: 'Glittering tunnels, razor crystal beasts.',
    levelMin: 50,
    levelMax: 60,
    basePower: 60,
    baseRewards: { exp: 130, copper: 128, skillExp: 30, statExp: 9 },
    enemies: [
      { id: 'maw', name: 'Crystal Maw', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'shard', name: 'Shardling', powerFactor: 0.9, hpFactor: 0.9, rewardFactor: 0.9 },
      { id: 'golem', name: 'Crystal Golem', powerFactor: 1.25, hpFactor: 1.3, rewardFactor: 1.25 },
    ],
  },
  {
    id: 'obsidian-badlands',
    name: 'Obsidian Badlands',
    description: 'Black glass dunes and fireborne.',
    levelMin: 56,
    levelMax: 66,
    basePower: 66,
    baseRewards: { exp: 144, copper: 150, skillExp: 32, statExp: 10 },
    enemies: [
      { id: 'hound', name: 'Obsidian Hound', powerFactor: 1.15, hpFactor: 1.05, rewardFactor: 1.15 },
      { id: 'basilisk', name: 'Glass Basilisk', powerFactor: 1.25, hpFactor: 1.2, rewardFactor: 1.25 },
      { id: 'raider', name: 'Ash Raider', powerFactor: 1.0, hpFactor: 0.95, rewardFactor: 1.0 },
    ],
  },
  {
    id: 'ancient-grove',
    name: 'Ancient Grove',
    description: 'World trees guarded by elder spirits.',
    levelMin: 62,
    levelMax: 72,
    basePower: 72,
    baseRewards: { exp: 160, copper: 176, skillExp: 34, statExp: 10 },
    enemies: [
      { id: 'guardian', name: 'Grove Guardian', powerFactor: 1.2, hpFactor: 1.25, rewardFactor: 1.2 },
      { id: 'archon', name: 'Ancient Archon', powerFactor: 1.3, hpFactor: 1.1, rewardFactor: 1.3 },
      { id: 'sprite', name: 'Verdant Sprite', powerFactor: 0.95, hpFactor: 0.9, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'frostfang-peaks',
    name: 'Frostfang Peaks',
    description: 'Frozen passes and ice-tusk beasts.',
    levelMin: 68,
    levelMax: 78,
    basePower: 78,
    baseRewards: { exp: 178, copper: 204, skillExp: 36, statExp: 11 },
    enemies: [
      { id: 'tusk', name: 'Frost Tusk', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'yeti', name: 'Ice Yeti', powerFactor: 1.3, hpFactor: 1.3, rewardFactor: 1.3 },
      { id: 'wisp', name: 'Frost Wisp', powerFactor: 0.9, hpFactor: 0.85, rewardFactor: 0.9 },
    ],
  },
  {
    id: 'bloodmoon-marsh',
    name: 'Bloodmoon Marsh',
    description: 'Cursed waters and moonlit predators.',
    levelMin: 74,
    levelMax: 84,
    basePower: 84,
    baseRewards: { exp: 196, copper: 236, skillExp: 38, statExp: 11 },
    enemies: [
      { id: 'stalker', name: 'Bloodmoon Stalker', powerFactor: 1.25, hpFactor: 1.1, rewardFactor: 1.25 },
      { id: 'wraith', name: 'Marsh Wraith', powerFactor: 1.15, hpFactor: 0.95, rewardFactor: 1.15 },
      { id: 'lurker', name: 'Moonlit Lurker', powerFactor: 1.05, hpFactor: 1.05, rewardFactor: 1.05 },
    ],
  },
  {
    id: 'celestial-ridge',
    name: 'Celestial Ridge',
    description: 'High ridges infused with star mana.',
    levelMin: 80,
    levelMax: 92,
    basePower: 92,
    baseRewards: { exp: 218, copper: 270, skillExp: 40, statExp: 12 },
    enemies: [
      { id: 'warden', name: 'Celestial Warden', powerFactor: 1.25, hpFactor: 1.2, rewardFactor: 1.25 },
      { id: 'saber', name: 'Star Saber', powerFactor: 1.15, hpFactor: 1.0, rewardFactor: 1.15 },
      { id: 'seer', name: 'Ridge Seer', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
    ],
  },
  {
    id: 'dragons-spine',
    name: "Dragon's Spine",
    description: 'The apex range where elder wyrms rule.',
    levelMin: 88,
    levelMax: 100,
    basePower: 100,
    baseRewards: { exp: 240, copper: 320, skillExp: 44, statExp: 12 },
    enemies: [
      { id: 'scion', name: 'Wyrm Scion', powerFactor: 1.3, hpFactor: 1.25, rewardFactor: 1.3 },
      { id: 'ancient', name: 'Ancient Drake', powerFactor: 1.35, hpFactor: 1.3, rewardFactor: 1.35 },
      { id: 'wyrmling', name: 'Feral Wyrmling', powerFactor: 1.15, hpFactor: 1.05, rewardFactor: 1.15 },
    ],
  },
]
