import type {
  ActionItem,
  ItemDef,
  Profession,
  ProfessionAction,
  ProfessionKey,
  Skill,
  SkillKey,
  Stat,
  StatKey,
  Zone,
  SeedItem,
} from './types'

export const createStats = (): Record<StatKey, Stat> => ({
  Strength: {
    name: 'Strength',
    value: 5,
    exp: 0,
    expToNext: 100,
    description: 'Power, lifting, melee force.',
  },
  Agility: {
    name: 'Agility',
    value: 5,
    exp: 0,
    expToNext: 100,
    description: 'Speed, reflexes, dexterity.',
  },
  Vitality: {
    name: 'Vitality',
    value: 5,
    exp: 0,
    expToNext: 100,
    description: 'Health, stamina, endurance.',
  },
  Spirit: {
    name: 'Spirit',
    value: 5,
    exp: 0,
    expToNext: 100,
    description: 'Mana, willpower, recovery.',
  },
  Intelligence: {
    name: 'Intelligence',
    value: 5,
    exp: 0,
    expToNext: 100,
    description: 'Knowledge, crafting, tactics.',
  },
})

export const createSkills = (): Record<SkillKey, Skill> => ({
  Combat: {
    name: 'Combat',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Weapon handling and battle instincts.',
  },
  Survival: {
    name: 'Survival',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Tracking, foraging, fieldcraft.',
  },
  Harvesting: {
    name: 'Harvesting',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Gathering resources and loot.',
  },
  Crafting: {
    name: 'Crafting',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Making gear and supplies.',
  },
  Arcana: {
    name: 'Arcana',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Mana control and spellwork.',
  },
})

export const createProfessions = (): Record<ProfessionKey, Profession> => ({
  Mining: {
    name: 'Mining',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Extract ore and crystals from the Land.',
    bonusLabel: 'Yield bonus',
    bonusPerLevel: 0.03,
  },
  Herbalism: {
    name: 'Herbalism',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Gather rare herbs and reagents.',
    bonusLabel: 'Yield bonus',
    bonusPerLevel: 0.03,
  },
  Smelting: {
    name: 'Smelting',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Refine ores into usable ingots.',
    bonusLabel: 'Output bonus',
    bonusPerLevel: 0.02,
  },
  Alchemy: {
    name: 'Alchemy',
    level: 0,
    exp: 0,
    expToNext: 100,
    description: 'Brew tonics and mana infusions.',
    bonusLabel: 'Potency bonus',
    bonusPerLevel: 0.02,
  },
})

export const createProfessionActions = (): ProfessionAction[] => [
  {
    id: 'mine-scrape',
    profession: 'Mining',
    name: 'Scrape the Vein',
    description: 'Chip away at exposed ore.',
    requiredLevel: 0,
    expGain: 4,
    rewards: [{ itemId: 'iron-ore', amount: 2 }],
  },
  {
    id: 'mine-deep',
    profession: 'Mining',
    name: 'Deep Vein',
    description: 'Push deeper for better ore.',
    requiredLevel: 6,
    expGain: 7,
    rewards: [
      { itemId: 'iron-ore', amount: 4 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
  },
  {
    id: 'herb-forage',
    profession: 'Herbalism',
    name: 'Forage Mist Herbs',
    description: 'Collect common herbs near the village.',
    requiredLevel: 0,
    expGain: 4,
    rewards: [{ itemId: 'mist-herb', amount: 3 }],
  },
  {
    id: 'herb-night',
    profession: 'Herbalism',
    name: 'Night Bloom Hunt',
    description: 'Hunt rare blooms at dusk.',
    requiredLevel: 5,
    expGain: 6,
    rewards: [
      { itemId: 'mist-herb', amount: 5 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
  },
  {
    id: 'smelt-iron',
    profession: 'Smelting',
    name: 'Smelt Iron',
    description: 'Refine ore into ingots.',
    requiredLevel: 0,
    expGain: 5,
    inputs: [{ itemId: 'iron-ore', amount: 3 }],
    rewards: [{ itemId: 'iron-ingot', amount: 1 }],
  },
  {
    id: 'smelt-pure',
    profession: 'Smelting',
    name: 'Purify Ingots',
    description: 'Produce higher quality ingots.',
    requiredLevel: 7,
    expGain: 8,
    inputs: [
      { itemId: 'iron-ore', amount: 6 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [{ itemId: 'iron-ingot', amount: 2 }],
  },
  {
    id: 'alchemy-tonic',
    profession: 'Alchemy',
    name: 'Brew Minor Tonic',
    description: 'Basic restorative mixture.',
    requiredLevel: 0,
    expGain: 5,
    inputs: [{ itemId: 'mist-herb', amount: 3 }],
    rewards: [{ itemId: 'minor-elixir', amount: 1 }],
  },
  {
    id: 'alchemy-focus',
    profession: 'Alchemy',
    name: 'Focus Draught',
    description: 'Infuse a drink with mana.',
    requiredLevel: 8,
    expGain: 9,
    inputs: [
      { itemId: 'mist-herb', amount: 6 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
    rewards: [
      { itemId: 'minor-elixir', amount: 2 },
      { itemId: 'mana-crystal', amount: 1 },
    ],
  },
]

export const createActions = (): ActionItem[] => [
  {
    id: 'train-strength',
    name: 'Train Strength',
    description: 'Lift, strike, and grind power gains.',
    gains: {
      exp: 5,
      stats: { Strength: 7, Vitality: 3 },
      skills: { Combat: 3 },
    },
  },
  {
    id: 'forest-run',
    name: 'Forest Run',
    description: 'Sprint and weave through the wilds.',
    gains: {
      exp: 4,
      stats: { Agility: 6, Vitality: 2 },
      skills: { Survival: 3 },
    },
  },
  {
    id: 'meditate',
    name: 'Meditate',
    description: 'Focus the core and gather mana.',
    gains: {
      exp: 3,
      stats: { Spirit: 7, Intelligence: 3 },
      skills: { Arcana: 4 },
    },
  },
  {
    id: 'gather',
    name: 'Gather Herbs',
    description: 'Idle harvesting for simple income.',
    gains: {
      exp: 2,
      stats: { Agility: 1, Intelligence: 2 },
      skills: { Harvesting: 5 },
    },
  },
  {
    id: 'craft',
    name: 'Craft Supplies',
    description: 'Turn finds into coin and skill.',
    gains: {
      exp: 3,
      stats: { Intelligence: 5 },
      skills: { Crafting: 5 },
    },
  },
]

export const createItemDefs = (): Record<string, ItemDef> => ({
  'mist-herb': {
    id: 'mist-herb',
    name: 'Mist Herb',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Foraging',
    description: 'A fragrant herb used in basic potions.',
    maxStack: 50,
    priceCopper: 1,
  },
  'goblin-ear': {
    id: 'goblin-ear',
    name: 'Goblin Ear',
    quality: 'Uncommon',
    type: 'Quest',
    subtype: 'Trophy',
    description: 'Proof of a goblin raid defeated.',
    maxStack: 20,
    priceCopper: 5,
  },
  'iron-ore': {
    id: 'iron-ore',
    name: 'Iron Ore',
    quality: 'Common',
    type: 'Resource',
    subtype: 'Mining',
    description: 'Raw ore ready for smelting.',
    maxStack: 50,
    priceCopper: 1,
  },
  'mana-crystal': {
    id: 'mana-crystal',
    name: 'Mana Crystal',
    quality: 'Rare',
    type: 'Resource',
    subtype: 'Arcana',
    description: 'A crystal infused with condensed mana.',
    maxStack: 10,
    priceCopper: 5,
  },
  'leather-helm': {
    id: 'leather-helm',
    name: 'Leather Helm',
    quality: 'Common',
    type: 'Equip',
    subtype: 'Helm',
    description: 'Basic protection for the head.',
    maxStack: 1,
    priceCopper: 25,
  },
  'iron-ingot': {
    id: 'iron-ingot',
    name: 'Iron Ingot',
    quality: 'Uncommon',
    type: 'Resource',
    subtype: 'Smelting',
    description: 'Refined metal ready for crafting.',
    maxStack: 50,
    priceCopper: 5,
  },
  'minor-elixir': {
    id: 'minor-elixir',
    name: 'Minor Elixir',
    quality: 'Uncommon',
    type: 'Consumable',
    subtype: 'Alchemy',
    description: 'A simple potion that refreshes vitality.',
    maxStack: 10,
    priceCopper: 20,
  },
})

export const seedInventoryItems: SeedItem[] = [
  { itemId: 'mist-herb', amount: 5 },
  { itemId: 'iron-ore', amount: 5 },
  { itemId: 'mana-crystal', amount: 2 },
]

export const createZones = (): Zone[] => [
  {
    id: 'mist-outskirts',
    name: 'Mist Village Outskirts',
    description: 'Wolves and bandits prowl the village edge.',
    levelMin: 1,
    levelMax: 5,
    basePower: 6,
    baseRewards: { exp: 16, copper: 10, skillExp: 6, statExp: 3 },
    enemies: [
      { id: 'wolf', name: 'Wild Wolf', powerFactor: 0.9, hpFactor: 0.9, rewardFactor: 0.9 },
      { id: 'bandit', name: 'Bandit Scout', powerFactor: 1.0, hpFactor: 1.0, rewardFactor: 1.0 },
      { id: 'boar', name: 'Dire Boar', powerFactor: 1.1, hpFactor: 1.15, rewardFactor: 1.1 },
    ],
  },
  {
    id: 'mist-forest',
    name: 'Mist Forest',
    description: 'Dense woods with lurking goblins.',
    levelMin: 4,
    levelMax: 8,
    basePower: 10,
    baseRewards: { exp: 22, copper: 14, skillExp: 7, statExp: 3 },
    enemies: [
      { id: 'goblin', name: 'Forest Goblin', powerFactor: 1.0, hpFactor: 0.95, rewardFactor: 1.0 },
      { id: 'stalker', name: 'Mist Stalker', powerFactor: 1.1, hpFactor: 1.05, rewardFactor: 1.1 },
      { id: 'spider', name: 'Shadow Spider', powerFactor: 0.95, hpFactor: 1.0, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'river-delle',
    name: 'River Delle',
    description: 'River spirits and crocodiles contest the banks.',
    levelMin: 7,
    levelMax: 12,
    basePower: 14,
    baseRewards: { exp: 28, copper: 18, skillExp: 8, statExp: 4 },
    enemies: [
      { id: 'croc', name: 'River Croc', powerFactor: 1.05, hpFactor: 1.15, rewardFactor: 1.1 },
      { id: 'sprite', name: 'River Sprite', powerFactor: 0.9, hpFactor: 0.85, rewardFactor: 0.9 },
      { id: 'lurker', name: 'Marsh Lurker', powerFactor: 1.0, hpFactor: 1.0, rewardFactor: 1.0 },
    ],
  },
  {
    id: 'goblin-warrens',
    name: 'Goblin Warrens',
    description: 'Tunnels under the hills, crawling with goblins.',
    levelMin: 10,
    levelMax: 15,
    basePower: 18,
    baseRewards: { exp: 34, copper: 24, skillExp: 10, statExp: 4 },
    enemies: [
      { id: 'raider', name: 'Goblin Raider', powerFactor: 1.0, hpFactor: 1.0, rewardFactor: 1.0 },
      { id: 'shaman', name: 'Goblin Shaman', powerFactor: 1.1, hpFactor: 0.95, rewardFactor: 1.1 },
      { id: 'brute', name: 'Goblin Brute', powerFactor: 1.2, hpFactor: 1.15, rewardFactor: 1.2 },
    ],
  },
  {
    id: 'shadow-fen',
    name: 'Shadow Fen',
    description: 'Swamp mists hide venom and undead.',
    levelMin: 14,
    levelMax: 20,
    basePower: 22,
    baseRewards: { exp: 40, copper: 30, skillExp: 12, statExp: 5 },
    enemies: [
      { id: 'stalker', name: 'Fen Stalker', powerFactor: 1.05, hpFactor: 1.0, rewardFactor: 1.05 },
      { id: 'bogwraith', name: 'Bog Wraith', powerFactor: 1.15, hpFactor: 0.9, rewardFactor: 1.15 },
      { id: 'slime', name: 'Toxic Slime', powerFactor: 0.95, hpFactor: 1.2, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'darkwood',
    name: 'Darkwood',
    description: 'Ancient trees and shadow beasts.',
    levelMin: 18,
    levelMax: 25,
    basePower: 26,
    baseRewards: { exp: 48, copper: 36, skillExp: 14, statExp: 5 },
    enemies: [
      { id: 'lynx', name: 'Shadow Lynx', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
      { id: 'treant', name: 'Darkwood Treant', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'shade', name: 'Night Shade', powerFactor: 1.0, hpFactor: 0.9, rewardFactor: 1.0 },
    ],
  },
  {
    id: 'stonefist-range',
    name: 'Stonefist Range',
    description: 'Rocky passes and ogre patrols.',
    levelMin: 22,
    levelMax: 30,
    basePower: 30,
    baseRewards: { exp: 58, copper: 44, skillExp: 16, statExp: 6 },
    enemies: [
      { id: 'ogre', name: 'Ogre Brute', powerFactor: 1.2, hpFactor: 1.25, rewardFactor: 1.2 },
      { id: 'bear', name: 'Stone Bear', powerFactor: 1.0, hpFactor: 1.1, rewardFactor: 1.0 },
      { id: 'raider', name: 'Cliff Raider', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
    ],
  },
  {
    id: 'silverpine-forest',
    name: 'Silverpine Forest',
    description: 'Silver bark and fey hunters.',
    levelMin: 26,
    levelMax: 34,
    basePower: 34,
    baseRewards: { exp: 66, copper: 52, skillExp: 18, statExp: 6 },
    enemies: [
      { id: 'fey', name: 'Fey Tracker', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
      { id: 'stag', name: 'Silver Stag', powerFactor: 0.95, hpFactor: 1.0, rewardFactor: 0.95 },
      { id: 'warden', name: 'Grove Warden', powerFactor: 1.15, hpFactor: 1.1, rewardFactor: 1.15 },
    ],
  },
  {
    id: 'great-plains',
    name: 'Great Plains',
    description: 'Stampedes and roaming beast packs.',
    levelMin: 30,
    levelMax: 38,
    basePower: 38,
    baseRewards: { exp: 74, copper: 60, skillExp: 20, statExp: 7 },
    enemies: [
      { id: 'ripper', name: 'Plains Ripper', powerFactor: 1.1, hpFactor: 1.0, rewardFactor: 1.1 },
      { id: 'hornbeast', name: 'Thunderhorn', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'scavenger', name: 'Sky Scavenger', powerFactor: 0.95, hpFactor: 0.9, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'ashen-barrens',
    name: 'Ashen Barrens',
    description: 'Scorched earth and ash drakes.',
    levelMin: 34,
    levelMax: 42,
    basePower: 42,
    baseRewards: { exp: 84, copper: 70, skillExp: 22, statExp: 7 },
    enemies: [
      { id: 'drake', name: 'Ash Drake', powerFactor: 1.2, hpFactor: 1.1, rewardFactor: 1.25 },
      { id: 'cinder', name: 'Cinder Hound', powerFactor: 1.0, hpFactor: 0.95, rewardFactor: 1.0 },
      { id: 'pyre', name: 'Pyre Elemental', powerFactor: 1.15, hpFactor: 1.2, rewardFactor: 1.2 },
    ],
  },
  {
    id: 'sunken-ruins',
    name: 'Sunken Ruins',
    description: 'Ancient halls submerged in mana tides.',
    levelMin: 38,
    levelMax: 46,
    basePower: 46,
    baseRewards: { exp: 94, copper: 82, skillExp: 24, statExp: 8 },
    enemies: [
      { id: 'sentinel', name: 'Ruins Sentinel', powerFactor: 1.15, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'warden', name: 'Abyss Warden', powerFactor: 1.1, hpFactor: 1.0, rewardFactor: 1.1 },
      { id: 'eel', name: 'Mana Eel', powerFactor: 0.95, hpFactor: 0.9, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'thunder-steppe',
    name: 'Thunder Steppe',
    description: 'Storm-charged beasts and lightning spirits.',
    levelMin: 42,
    levelMax: 50,
    basePower: 50,
    baseRewards: { exp: 104, copper: 94, skillExp: 26, statExp: 8 },
    enemies: [
      { id: 'charger', name: 'Storm Charger', powerFactor: 1.2, hpFactor: 1.1, rewardFactor: 1.2 },
      { id: 'sprite', name: 'Lightning Sprite', powerFactor: 0.95, hpFactor: 0.85, rewardFactor: 0.95 },
      { id: 'howler', name: 'Thunder Howler', powerFactor: 1.1, hpFactor: 1.05, rewardFactor: 1.1 },
    ],
  },
  {
    id: 'wyvern-cliffs',
    name: 'Wyvern Cliffs',
    description: 'Sheer cliffs ruled by winged predators.',
    levelMin: 46,
    levelMax: 54,
    basePower: 54,
    baseRewards: { exp: 116, copper: 110, skillExp: 28, statExp: 9 },
    enemies: [
      { id: 'wyvern', name: 'Cliff Wyvern', powerFactor: 1.2, hpFactor: 1.15, rewardFactor: 1.2 },
      { id: 'harpy', name: 'Sky Harpy', powerFactor: 1.05, hpFactor: 0.9, rewardFactor: 1.05 },
      { id: 'eagle', name: 'Ridge Eagle', powerFactor: 0.95, hpFactor: 0.85, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'crystal-caverns',
    name: 'Crystal Caverns',
    description: 'Glittering tunnels, razor crystal beasts.',
    levelMin: 50,
    levelMax: 60,
    basePower: 60,
    baseRewards: { exp: 130, copper: 128, skillExp: 30, statExp: 9 },
    enemies: [
      { id: 'maw', name: 'Crystal Maw', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'shard', name: 'Shardling', powerFactor: 0.9, hpFactor: 0.9, rewardFactor: 0.9 },
      { id: 'golem', name: 'Crystal Golem', powerFactor: 1.25, hpFactor: 1.3, rewardFactor: 1.25 },
    ],
  },
  {
    id: 'obsidian-badlands',
    name: 'Obsidian Badlands',
    description: 'Black glass dunes and fireborne.',
    levelMin: 56,
    levelMax: 66,
    basePower: 66,
    baseRewards: { exp: 144, copper: 150, skillExp: 32, statExp: 10 },
    enemies: [
      { id: 'hound', name: 'Obsidian Hound', powerFactor: 1.15, hpFactor: 1.05, rewardFactor: 1.15 },
      { id: 'basilisk', name: 'Glass Basilisk', powerFactor: 1.25, hpFactor: 1.2, rewardFactor: 1.25 },
      { id: 'raider', name: 'Ash Raider', powerFactor: 1.0, hpFactor: 0.95, rewardFactor: 1.0 },
    ],
  },
  {
    id: 'ancient-grove',
    name: 'Ancient Grove',
    description: 'World trees guarded by elder spirits.',
    levelMin: 62,
    levelMax: 72,
    basePower: 72,
    baseRewards: { exp: 160, copper: 176, skillExp: 34, statExp: 10 },
    enemies: [
      { id: 'guardian', name: 'Grove Guardian', powerFactor: 1.2, hpFactor: 1.25, rewardFactor: 1.2 },
      { id: 'archon', name: 'Ancient Archon', powerFactor: 1.3, hpFactor: 1.1, rewardFactor: 1.3 },
      { id: 'sprite', name: 'Verdant Sprite', powerFactor: 0.95, hpFactor: 0.9, rewardFactor: 0.95 },
    ],
  },
  {
    id: 'frostfang-peaks',
    name: 'Frostfang Peaks',
    description: 'Frozen passes and ice-tusk beasts.',
    levelMin: 68,
    levelMax: 78,
    basePower: 78,
    baseRewards: { exp: 178, copper: 204, skillExp: 36, statExp: 11 },
    enemies: [
      { id: 'tusk', name: 'Frost Tusk', powerFactor: 1.2, hpFactor: 1.2, rewardFactor: 1.2 },
      { id: 'yeti', name: 'Ice Yeti', powerFactor: 1.3, hpFactor: 1.3, rewardFactor: 1.3 },
      { id: 'wisp', name: 'Frost Wisp', powerFactor: 0.9, hpFactor: 0.85, rewardFactor: 0.9 },
    ],
  },
  {
    id: 'bloodmoon-marsh',
    name: 'Bloodmoon Marsh',
    description: 'Cursed waters and moonlit predators.',
    levelMin: 74,
    levelMax: 84,
    basePower: 84,
    baseRewards: { exp: 196, copper: 236, skillExp: 38, statExp: 11 },
    enemies: [
      { id: 'stalker', name: 'Bloodmoon Stalker', powerFactor: 1.25, hpFactor: 1.1, rewardFactor: 1.25 },
      { id: 'wraith', name: 'Marsh Wraith', powerFactor: 1.15, hpFactor: 0.95, rewardFactor: 1.15 },
      { id: 'lurker', name: 'Moonlit Lurker', powerFactor: 1.05, hpFactor: 1.05, rewardFactor: 1.05 },
    ],
  },
  {
    id: 'celestial-ridge',
    name: 'Celestial Ridge',
    description: 'High ridges infused with star mana.',
    levelMin: 80,
    levelMax: 92,
    basePower: 92,
    baseRewards: { exp: 218, copper: 270, skillExp: 40, statExp: 12 },
    enemies: [
      { id: 'warden', name: 'Celestial Warden', powerFactor: 1.25, hpFactor: 1.2, rewardFactor: 1.25 },
      { id: 'saber', name: 'Star Saber', powerFactor: 1.15, hpFactor: 1.0, rewardFactor: 1.15 },
      { id: 'seer', name: 'Ridge Seer', powerFactor: 1.05, hpFactor: 0.95, rewardFactor: 1.05 },
    ],
  },
  {
    id: 'dragons-spine',
    name: "Dragon's Spine",
    description: 'The apex range where elder wyrms rule.',
    levelMin: 88,
    levelMax: 100,
    basePower: 100,
    baseRewards: { exp: 240, copper: 320, skillExp: 44, statExp: 12 },
    enemies: [
      { id: 'scion', name: 'Wyrm Scion', powerFactor: 1.3, hpFactor: 1.25, rewardFactor: 1.3 },
      { id: 'ancient', name: 'Ancient Drake', powerFactor: 1.35, hpFactor: 1.3, rewardFactor: 1.35 },
      { id: 'wyrmling', name: 'Feral Wyrmling', powerFactor: 1.15, hpFactor: 1.05, rewardFactor: 1.15 },
    ],
  },
]
